version: '3.4'
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build:
      context: ./myfirstsite
      dockerfile: Dockerfile.prod
    command: gunicorn myfirstsite.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
   