# Generated by Django 2.2.17 on 2020-11-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='protein',
        ),
    ]
