# Generated by Django 2.2.17 on 2020-11-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20201114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientofdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='restaurant.Dish'),
        ),
        migrations.AlterField(
            model_name='ingridientofdish',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient', to='restaurant.Ingridient'),
        ),
    ]
