# Generated by Django 2.2.17 on 2020-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='restaurant/static/images/Cursed Cat _ Cursed Cat.jpeg', upload_to='images/'),
        ),
    ]
