# Generated by Django 2.2.17 on 2020-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20201115_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='images/cat.jpeg', upload_to=''),
        ),
    ]
