# Generated by Django 2.2.17 on 2020-11-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20201115_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='restaurant/static/images/cat.jpeg', upload_to=''),
        ),
    ]
