# Generated by Django 2.2.17 on 2020-11-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20201115_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='restaurant/static/media/cat.jpeg', upload_to='restaurant/static/media'),
        ),
    ]
