# Generated by Django 2.2.17 on 2020-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20201115_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='media/cat.jpeg', upload_to='media/'),
        ),
    ]
